# Generated by Django 3.0.2 on 2020-02-03 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='comments',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='completedby',
            field=models.CharField(blank=True, max_length=50, verbose_name='completedby'),
        ),
    ]
