# Generated by Django 3.0.2 on 2020-02-03 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_task', '0002_auto_20200203_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='time',
        ),
    ]
