# Generated by Django 3.0.2 on 2020-02-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_task', '0003_auto_20200203_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
