# Generated by Django 3.0.2 on 2020-02-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_task', '0004_auto_20200203_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('termindate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
