# Generated by Django 3.0.2 on 2020-02-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_task', '0005_stafflist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
