# Generated by Django 3.0.2 on 2020-02-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_task', '0006_auto_20200204_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='date',
            new_name='taskdate',
        ),
        migrations.RenameField(
            model_name='tasklist',
            old_name='datetime',
            new_name='taskdatetime',
        ),
        migrations.RenameField(
            model_name='tasklist',
            old_name='time',
            new_name='tasktime',
        ),
    ]
