# Generated by Django 3.0.2 on 2020-02-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_task', '0007_auto_20200204_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='taskdatetime',
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='comments',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='completedby',
            field=models.CharField(max_length=50, null=True, verbose_name='completedby'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='taskdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='tasktime',
            field=models.TimeField(),
        ),
    ]
