# Generated by Django 3.0.2 on 2020-02-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_task', '0008_auto_20200204_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='tasktime',
            field=models.TimeField(blank=True),
        ),
    ]
