# Generated by Django 3.0.2 on 2020-02-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_task', '0009_auto_20200204_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='comments',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='completedby',
            field=models.CharField(blank=True, max_length=50, verbose_name='completedby'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='taskdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='tasktime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
