# Generated by Django 3.0.2 on 2020-02-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_task', '0010_auto_20200204_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='taskdate',
            field=models.DateField(),
        ),
    ]
