# Generated by Django 3.0.2 on 2020-02-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_task', '0011_auto_20200204_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafflist',
            name='staffaddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stafflist',
            name='staffcontract',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stafflist',
            name='staffdob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stafflist',
            name='staffemail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stafflist',
            name='staffphone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stafflist',
            name='staffqual',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
