# Generated by Django 3.0.2 on 2020-02-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_task', '0012_auto_20200204_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stafflist',
            old_name='firstname',
            new_name='staffname',
        ),
        migrations.RemoveField(
            model_name='stafflist',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='stafflist',
            name='staffaddress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stafflist',
            name='staffcontract',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stafflist',
            name='staffemail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stafflist',
            name='staffphone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stafflist',
            name='staffqual',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
