# Generated by Django 3.0.2 on 2020-02-10 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_task', '0013_auto_20200210_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='assingees',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
