# Generated by Django 3.0.2 on 2020-02-10 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module_task', '0015_auto_20200210_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='completedby',
        ),
    ]
